"""Country（国家）双语选项映射：短名 ↔ English（中文）。

内部推断 / 询盘标签仍用中文短名；写入飞书主表时用 to_write_country。
"""

from __future__ import annotations

import re

COUNTRY_SHORT_TO_WRITE: dict[str, str] = {
    '不丹': 'Bhutan（不丹）',
    '东帝汶': 'Timor-Leste（东帝汶）',
    '中东': 'Middle East（中东）',
    '中亚': 'Central Asia（中亚）',
    '中国': 'China（中国）',
    '中国香港': 'Hong Kong（中国香港）',
    '中非共和国': 'Central African Republic（中非共和国）',
    '丹麦': 'Denmark（丹麦）',
    '乌克兰': 'Ukraine（乌克兰）',
    '乌兹别克斯坦': 'Uzbekistan（乌兹别克斯坦）',
    '乌干达': 'Uganda（乌干达）',
    '乌拉圭': 'Uruguay（乌拉圭）',
    '乍得': 'Chad（乍得）',
    '也门': 'Yemen（也门）',
    '亚美尼亚': 'Armenia（亚美尼亚）',
    '以色列': 'Israel（以色列）',
    '伊拉克': 'Iraq（伊拉克）',
    '伊朗': 'Iran（伊朗）',
    '伯利兹': 'Belize（伯利兹）',
    '佛得角': 'Cabo Verde（佛得角）',
    '俄罗斯': 'Russia（俄罗斯）',
    '保加利亚': 'Bulgaria（保加利亚）',
    '克罗地亚': 'Croatia（克罗地亚）',
    '冈比亚': 'Gambia（冈比亚）',
    '冰岛': 'Iceland（冰岛）',
    '几内亚': 'Guinea（几内亚）',
    '几内亚比绍': 'Guinea-Bissau（几内亚比绍）',
    '列支敦士登': 'Liechtenstein（列支敦士登）',
    '刚果': 'Congo（刚果）',
    '利比亚': 'Libya（利比亚）',
    '利比里亚': 'Liberia（利比里亚）',
    '加拿大': 'Canada（加拿大）',
    '加纳': 'Ghana（加纳）',
    '加蓬': 'Gabon（加蓬）',
    '匈牙利': 'Hungary（匈牙利）',
    '北马其顿': 'North Macedonia（北马其顿）',
    '南美': 'South America（南美）',
    '南苏丹': 'South Sudan（南苏丹）',
    '南非': 'South Africa（南非）',
    '博茨瓦纳': 'Botswana（博茨瓦纳）',
    '卡塔尔': 'Qatar（卡塔尔）',
    '卢旺达': 'Rwanda（卢旺达）',
    '卢森堡': 'Luxembourg（卢森堡）',
    '印度': 'India（印度）',
    '印度尼西亚': 'Indonesia（印度尼西亚）',
    '危地马拉': 'Guatemala（危地马拉）',
    '厄瓜多尔': 'Ecuador（厄瓜多尔）',
    '厄立特里亚': 'Eritrea（厄立特里亚）',
    '叙利亚': 'Syria（叙利亚）',
    '古巴': 'Cuba（古巴）',
    '台湾': 'Taiwan（台湾）',
    '吉尔吉斯斯坦': 'Kyrgyzstan（吉尔吉斯斯坦）',
    '吉布提': 'Djibouti（吉布提）',
    '哈萨克斯坦': 'Kazakhstan（哈萨克斯坦）',
    '哥伦比亚': 'Colombia（哥伦比亚）',
    '哥斯达黎加': 'Costa Rica（哥斯达黎加）',
    '喀麦隆': 'Cameroon（喀麦隆）',
    '图瓦卢': 'Tuvalu（图瓦卢）',
    '土库曼斯坦': 'Turkmenistan（土库曼斯坦）',
    '土耳其': 'Turkey（土耳其）',
    '圣卢西亚': 'Saint Lucia（圣卢西亚）',
    '圣基茨和尼维斯': 'Saint Kitts and Nevis（圣基茨和尼维斯）',
    '圣多美和普林西比': 'Sao Tome and Principe（圣多美和普林西比）',
    '圣文森特和格林纳丁斯': 'Saint Vincent and the Grenadines（圣文森特和格林纳丁斯）',
    '圣马力诺': 'San Marino（圣马力诺）',
    '圭亚那': 'Guyana（圭亚那）',
    '坦桑尼亚': 'Tanzania（坦桑尼亚）',
    '埃及': 'Egypt（埃及）',
    '埃塞俄比亚': 'Ethiopia（埃塞俄比亚）',
    '基里巴斯': 'Kiribati（基里巴斯）',
    '塔吉克斯坦': 'Tajikistan（塔吉克斯坦）',
    '塞内加尔': 'Senegal（塞内加尔）',
    '塞尔维亚': 'Serbia（塞尔维亚）',
    '塞拉利昂': 'Sierra Leone（塞拉利昂）',
    '塞浦路斯': 'Cyprus（塞浦路斯）',
    '塞舌尔': 'Seychelles（塞舌尔）',
    '墨西哥': 'Mexico（墨西哥）',
    '多哥': 'Togo（多哥）',
    '多明尼加共和国': 'Dominican Republic（多明尼加共和国）',
    '多米尼克': 'Dominica（多米尼克）',
    '大洋洲 法属波利尼西亚': 'French Polynesia（大洋洲 法属波利尼西亚）',
    '奥地利': 'Austria（奥地利）',
    '委内瑞拉': 'Venezuela（委内瑞拉）',
    '孟加拉国': 'Bangladesh（孟加拉国）',
    '安哥拉': 'Angola（安哥拉）',
    '安提瓜和巴布达': 'Antigua and Barbuda（安提瓜和巴布达）',
    '安道尔': 'Andorra（安道尔）',
    '密克罗尼西亚': 'Micronesia（密克罗尼西亚）',
    '尼加拉瓜': 'Nicaragua（尼加拉瓜）',
    '尼日利亚': 'Nigeria（尼日利亚）',
    '尼日尔': 'Niger（尼日尔）',
    '尼泊尔': 'Nepal（尼泊尔）',
    '巴勒斯坦': 'Palestine（巴勒斯坦）',
    '巴哈马': 'Bahamas（巴哈马）',
    '巴基斯坦': 'Pakistan（巴基斯坦）',
    '巴巴多斯': 'Barbados（巴巴多斯）',
    '巴布亚新几内亚': 'Papua New Guinea（巴布亚新几内亚）',
    '巴拉圭': 'Paraguay（巴拉圭）',
    '巴拿马': 'Panama（巴拿马）',
    '巴林': 'Bahrain（巴林）',
    '巴西': 'Brazil（巴西）',
    '布基纳法索': 'Burkina Faso（布基纳法索）',
    '布隆迪': 'Burundi（布隆迪）',
    '希腊': 'Greece（希腊）',
    '帕劳': 'Palau（帕劳）',
    '开曼群岛': 'Cayman Islands（开曼群岛）',
    '德国': 'Germany（德国）',
    '意大利': 'Italy（意大利）',
    '所罗门群岛': 'Solomon Islands（所罗门群岛）',
    '拉脱维亚': 'Latvia（拉脱维亚）',
    '挪威': 'Norway（挪威）',
    '捷克': 'Czechia（捷克）',
    '摩尔多瓦': 'Moldova（摩尔多瓦）',
    '摩洛哥': 'Morocco（摩洛哥）',
    '摩纳哥': 'Monaco（摩纳哥）',
    '文莱': 'Brunei（文莱）',
    '斐济': 'Fiji（斐济）',
    '斯威士兰': 'Eswatini（斯威士兰）',
    '斯洛伐克': 'Slovakia（斯洛伐克）',
    '斯洛文尼亚': 'Slovenia（斯洛文尼亚）',
    '斯里兰卡': 'Sri Lanka（斯里兰卡）',
    '新加坡': 'Singapore（新加坡）',
    '新西兰': 'New Zealand（新西兰）',
    '无可用选项': 'No options available（无可用选项）',
    '无法识别': 'Unrecognized（无法识别）',
    '日本': 'Japan（日本）',
    '智利': 'Chile（智利）',
    '朝鲜': 'North Korea（朝鲜）',
    '柬埔寨': 'Cambodia（柬埔寨）',
    '根西岛': 'Guernsey（根西岛）',
    '格林纳达': 'Grenada（格林纳达）',
    '格鲁吉亚': 'Georgia（格鲁吉亚）',
    '梵蒂冈': 'Vatican City（梵蒂冈）',
    '欧洲': 'Europe（欧洲）',
    '比利时': 'Belgium（比利时）',
    '毛里塔尼亚': 'Mauritania（毛里塔尼亚）',
    '毛里求斯': 'Mauritius（毛里求斯）',
    '汤加': 'Tonga（汤加）',
    '沙特': 'Saudi Arabia（沙特）',
    '沙特阿拉伯': 'Saudi Arabia（沙特阿拉伯）',
    '法国': 'France（法国）',
    '法属圭亚那': 'French Guiana（法属圭亚那）',
    '法罗群岛': 'Faroe Islands（法罗群岛）',
    '波兰': 'Poland（波兰）',
    '波多黎各': 'Puerto Rico（波多黎各）',
    '波多黎各 美国': 'Puerto Rico（波多黎各 美国）',
    '波斯尼亚和黑塞哥维那': 'Bosnia and Herzegovina（波斯尼亚和黑塞哥维那）',
    '泰国': 'Thailand（泰国）',
    '泽西岛': 'Jersey（泽西岛）',
    '津巴布韦': 'Zimbabwe（津巴布韦）',
    '洪都拉斯': 'Honduras（洪都拉斯）',
    '海地': 'Haiti（海地）',
    '澳大利亚': 'Australia（澳大利亚）',
    '澳门': 'Macao（澳门）',
    '爱尔兰': 'Ireland（爱尔兰）',
    '爱沙尼亚': 'Estonia（爱沙尼亚）',
    '牙买加': 'Jamaica（牙买加）',
    '特克斯和凯科斯群岛': 'Turks and Caicos Islands（特克斯和凯科斯群岛）',
    '特立尼达和多巴哥': 'Trinidad and Tobago（特立尼达和多巴哥）',
    '玻利维亚': 'Bolivia（玻利维亚）',
    '瑙鲁': 'Nauru（瑙鲁）',
    '瑞典': 'Sweden（瑞典）',
    '瑞士': 'Switzerland（瑞士）',
    '瓦努阿图': 'Vanuatu（瓦努阿图）',
    '留尼汪': 'Réunion（留尼汪）',
    '白俄罗斯': 'Belarus（白俄罗斯）',
    '百慕大群岛': 'Bermuda（百慕大群岛）',
    '直布罗陀': 'Gibraltar（直布罗陀）',
    '科威特': 'Kuwait（科威特）',
    '科摩罗': 'Comoros（科摩罗）',
    '科特迪瓦': "Côte d'Ivoire（科特迪瓦）",
    '科索沃': 'Kosovo（科索沃）',
    '秘鲁': 'Peru（秘鲁）',
    '突尼斯': 'Tunisia（突尼斯）',
    '立陶宛': 'Lithuania（立陶宛）',
    '索马里': 'Somalia（索马里）',
    '约旦': 'Jordan（约旦）',
    '纳米比亚': 'Namibia（纳米比亚）',
    '缅甸': 'Myanmar（缅甸）',
    '罗马尼亚': 'Romania（罗马尼亚）',
    '美国': 'United States（美国）',
    '老挝': 'Laos（老挝）',
    '肯尼亚': 'Kenya（肯尼亚）',
    '芬兰': 'Finland（芬兰）',
    '苏丹': 'Sudan（苏丹）',
    '苏里南': 'Suriname（苏里南）',
    '英国': 'United Kingdom（英国）',
    '荷兰': 'Netherlands（荷兰）',
    '荷属圣马丁': 'Sint Maarten（荷属圣马丁）',
    '荷属安的列斯': 'Netherlands Antilles（荷属安的列斯）',
    '莫桑比克': 'Mozambique（莫桑比克）',
    '莱索托': 'Lesotho（莱索托）',
    '菲律宾': 'Philippines（菲律宾）',
    '萨尔瓦多': 'El Salvador（萨尔瓦多）',
    '萨摩亚': 'Samoa（萨摩亚）',
    '葡萄牙': 'Portugal（葡萄牙）',
    '蒙古': 'Mongolia（蒙古）',
    '西班牙': 'Spain（西班牙）',
    '贝宁': 'Benin（贝宁）',
    '赞比亚': 'Zambia（赞比亚）',
    '赤道几内亚': 'Equatorial Guinea（赤道几内亚）',
    '越南': 'Vietnam（越南）',
    '阿塞拜疆': 'Azerbaijan（阿塞拜疆）',
    '阿富汗': 'Afghanistan（阿富汗）',
    '阿尔及利亚': 'Algeria（阿尔及利亚）',
    '阿尔巴尼亚': 'Albania（阿尔巴尼亚）',
    '阿曼': 'Oman（阿曼）',
    '阿根廷': 'Argentina（阿根廷）',
    '阿爾巴尼亞': 'Albania（阿爾巴尼亞）',
    '阿联酋': 'United Arab Emirates（阿联酋）',
    '阿鲁巴': 'Aruba（阿鲁巴）',
    '非洲': 'Africa（非洲）',
    '韩国': 'South Korea（韩国）',
    '香港': 'Hong Kong（香港）',
    '马尔代夫': 'Maldives（马尔代夫）',
    '马恩岛': 'Isle of Man（马恩岛）',
    '马拉维': 'Malawi（马拉维）',
    '马来西亚': 'Malaysia（马来西亚）',
    '马绍尔群岛': 'Marshall Islands（马绍尔群岛）',
    '马耳他': 'Malta（马耳他）',
    '马达加斯加': 'Madagascar（马达加斯加）',
    '马里': 'Mali（马里）',
    '黎巴嫩': 'Lebanon（黎巴嫩）',
    '黑山': 'Montenegro（黑山）',
}

# 常见别名 → 规范短名（再转双语）
COUNTRY_ALIASES_TO_SHORT: dict[str, str] = {
    "USA": "美国",
    "US": "美国",
    "United States": "美国",
    "UK": "英国",
    "United Kingdom": "英国",
    "UAE": "阿联酋",
    "HK": "香港",
    "Hong Kong": "香港",
    "印尼": "印度尼西亚",
    "沙特": "沙特阿拉伯",
    "波黑": "波斯尼亚和黑塞哥维那",
    "孟加拉": "孟加拉国",
}

_WRITE_TO_SHORT = {v: k for k, v in COUNTRY_SHORT_TO_WRITE.items()}
_PAREN_RE = re.compile(r"（([^）]+)）\s*$")


def normalize_country_short(country: str) -> str:
    """双语/英文/别名 → 中文短名。"""
    c = (country or "").strip()
    if not c:
        return ""
    if c in COUNTRY_SHORT_TO_WRITE:
        return c
    if c in _WRITE_TO_SHORT:
        return _WRITE_TO_SHORT[c]
    if c in COUNTRY_ALIASES_TO_SHORT:
        return COUNTRY_ALIASES_TO_SHORT[c]
    m = _PAREN_RE.search(c)
    if m:
        inner = m.group(1).strip()
        if inner in COUNTRY_SHORT_TO_WRITE:
            return inner
    # 大小写不敏感英文别名
    low = c.lower()
    for alias, short in COUNTRY_ALIASES_TO_SHORT.items():
        if alias.lower() == low:
            return short
    return c


def to_write_country(country: str) -> str:
    """任意国家别名 → 主表双语写入名；无法映射时原样返回。"""
    c = (country or "").strip()
    if not c:
        return ""
    if c in _WRITE_TO_SHORT or c in COUNTRY_SHORT_TO_WRITE.values():
        return c if c in COUNTRY_SHORT_TO_WRITE.values() else COUNTRY_SHORT_TO_WRITE.get(_WRITE_TO_SHORT.get(c, ""), c)
    short = normalize_country_short(c)
    return COUNTRY_SHORT_TO_WRITE.get(short, c)


INVALID_COUNTRY_VALUES = frozenset({
    "",
    "无法识别",
    "Unrecognized",
    "Unrecognized（无法识别）",
    "无可用选项",
    "No options available",
    "No options available（无可用选项）",
    "Unknown",
    "N/A",
})

